build_from:
  aarch64: "gladysassistant/gladys:v4"
  amd64: "gladysassistant/gladys:v4"
  armv7: "gladysassistant/gladys:v4"
args:
  BUILD_ARCH: "{arch}"
  BUILD_DATE: "{date}"
  BUILD_DESCRIPTION: "A privacy-first, open-source home automation software"
  BUILD_NAME: "Gladys Assistant"
  BUILD_REF: "{ref}"
  BUILD_REPOSITORY: "GladysAssistant/hassio-addon-gladys"
  BUILD_VERSION: "{version}"
